spring:
  data:
    redis:
      host: 192.168.191.80
      port: 6379
      password: ceIRWJaqbEfPPY5E
      database: 15
  datasource:
    dynamic:
      hikari: # Hikari 连接池全局配置
        connection-timeout: 30000     # 等待连接池分配链接的最大时长（毫秒），超过这个时长还没有可用的连接则发生 SQLException，默认：30 秒
        minimum-idle: 2               # 最小空闲连接数
        maximum-pool-size: 10         # 最大连接数
        idle-timeout: 600000          # 连接超时的最大时长（毫秒），超时则被释放（retired），默认：10 分钟
        max-lifetime: 1800000         # 连接的生命时长（毫秒），超时而且没被使用则被释放（retired），默认： 30 分钟
        connection-test-query: SELECT 1
      primary: admin
      datasource:
        admin:
          driver-class-name: com.mysql.cj.jdbc.Driver
          url: jdbc:mysql://192.168.191.80:3306/wr-chat-shejiao?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai&nullCatalogMeansCurrent=true
          username: wr-chat-shejiao
          password: t5hmWrBKj6Z7S6JJ
        platform:
          driver-class-name: com.mysql.cj.jdbc.Driver
          url: jdbc:mysql://192.168.191.80:3306/wr-chat-shejiao?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai&nullCatalogMeansCurrent=true
          username: wr-chat-shejiao
          password: t5hmWrBKj6Z7S6JJ

minio:
  endpoint: http://192.168.191.80:19000 #内网地址
  domain: https://local80minio.gzwrxxkj.com  #外网访问地址
  accessKey: box-im
  secretKey: box-im-12345678
  bucketName: box-im
  imagePath: image
  filePath: file
  videoPath: video