server:
  port: 6666
  servlet:
    context-path: /packet
spring:
  redis:
    port: 6379
    host: 192.168.191.80
    database: 15
    password: ceIRWJaqbEfPPY5E
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.191.80:3306/wr-chat
    username: wr-chat
    password: r6PJhh8ZxA7rbNrM
mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl




